AKA-1 Create Customer tests
martinhel2001/AutomationFramework pull request #21
Opened 2024-01-10 17:26 UTC by Kyrevam

It includes the test cases for Creating a New Customer in Akaunting platform

2024-01-10 17:38 UTC, martinhel2001 requested changes
Guille pls verify all my comments

2024-01-10 17:38 UTC, martinhel2001 commented on .gitignore
This file should not be included in the PR

2024-01-10 17:38 UTC, martinhel2001 commented on Automation-Campus.iml
This file should not be included in the PR

2024-01-10 17:38 UTC, martinhel2001 commented on Logs/Webliv_Automation_Logs.log
This file should not be included in the PR

2024-01-10 17:38 UTC, martinhel2001 commented on extent-reports/extent-report.html
This file should not be included in the PR

2024-01-10 17:38 UTC, martinhel2001 commented on target/classes/baseMain/TestsConfigReader.class
This file should not be included in the PR

2024-01-10 17:38 UTC, martinhel2001 commented on src/main/java/dataentities/akaunting/Customer.java
> +    @Setter @Getter private String Address="123 Elm Street";
The @Setter is not needed

2024-01-16 16:28 UTC, Kyrevam commented on .gitignore
This is done.

2024-01-16 16:28 UTC, Kyrevam commented on Automation-Campus.iml
This is done.

2024-01-16 16:28 UTC, Kyrevam commented on extent-reports/extent-report.html
This is done.

2024-01-16 16:28 UTC, Kyrevam commented on target/classes/baseMain/TestsConfigReader.class
This is done.

2024-01-16 16:28 UTC, Kyrevam commented on src/main/java/dataentities/akaunting/Customer.java
> +    @Setter @Getter private String Address="123 Elm Street";
This is done.

2024-01-16 19:09 UTC, martinhel2001 approved these changes

2024-01-16 19:10 UTC, merged